name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitLab Container Registry
        run: echo ${{ secrets.GITLAB_REGISTRY_PASSWORD }} | docker login ${{ secrets.GITLAB_REGISTRY }} -u ${{ secrets.GITLAB_REGISTRY_USER }} --password-stdin

      - name: Pull cache image
        run: |
          docker pull ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache || true

      - name: Build and push cache image
        run: |
          docker build --target build --cache-from ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache -t ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache .
          docker push ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache
        if: github.event_name == 'push'

  release-develop:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitLab Container Registry
        run: echo ${{ secrets.GITLAB_REGISTRY_PASSWORD }} | docker login ${{ secrets.GITLAB_REGISTRY }} -u ${{ secrets.GITLAB_REGISTRY_USER }} --password-stdin

      - name: Build and push dev image
        run: |
          docker build --pull --cache-from ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache -t ${{ VARS.CI_REGISTRY_IMAGE }}:dev-${{ github.sha }} --build-arg DATABASE_URL_BUILD=${{ secrets.DATABASE_URL_DEV }} .
          docker push ${{ VARS.CI_REGISTRY_IMAGE }}:dev-${{ github.sha }}

      - name: Log in to DigitalOcean Registry
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin

      - name: Tag and push to DigitalOcean Registry
        run: |
          docker tag ${{ VARS.CI_REGISTRY_IMAGE }}:dev-${{ github.sha }} registry.digitalocean.com/${{ vars.IMAGE_NAME }}/dev:latest
          docker push registry.digitalocean.com/${{ vars.IMAGE_NAME }}/dev:latest

      - name: Deploy to DigitalOcean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_DEV_APP_ID }}
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  release-uat:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitLab Container Registry
        run: echo ${{ secrets.GITLAB_REGISTRY_PASSWORD }} | docker login ${{ secrets.GITLAB_REGISTRY }} -u ${{ secrets.GITLAB_REGISTRY_USER }} --password-stdin

      - name: Build and push uat image
        run: |
          docker build --pull --cache-from ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache -t ${{ VARS.CI_REGISTRY_IMAGE }}:uat-${{ github.sha }} --build-arg DATABASE_URL_BUILD=${{ secrets.DATABASE_URL_UAT }} .
          docker push ${{ VARS.CI_REGISTRY_IMAGE }}:uat-${{ github.sha }}

      - name: Log in to DigitalOcean Registry
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin

      - name: Tag and push to DigitalOcean Registry
        run: |
          docker tag ${{ VARS.CI_REGISTRY_IMAGE }}:uat-${{ github.sha }} registry.digitalocean.com/${{ vars.IMAGE_NAME }}/uat:latest
          docker push registry.digitalocean.com/${{ vars.IMAGE_NAME }}/uat:latest

      - name: Deploy to DigitalOcean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_UAT_APP_ID }}
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  release-prod:
    runs-on: ubuntu-latest
    needs: install-dependencies
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitLab Container Registry
        run: echo ${{ secrets.GITLAB_REGISTRY_PASSWORD }} | docker login ${{ secrets.GITLAB_REGISTRY }} -u ${{ secrets.GITLAB_REGISTRY_USER }} --password-stdin

      - name: Build and push prod image
        run: |
          docker build --pull --cache-from ${{ VARS.CI_REGISTRY_IMAGE }}:${{ github.sha }}-cache -t ${{ VARS.CI_REGISTRY_IMAGE }}:prod-${{ github.sha }} --build-arg DATABASE_URL_BUILD=${{ secrets.DATABASE_URL_PROD }} .
          docker push ${{ VARS.CI_REGISTRY_IMAGE }}:prod-${{ github.sha }}

      - name: Log in to DigitalOcean Registry
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} --password-stdin

      - name: Tag and push to DigitalOcean Registry
        run: |
          docker tag ${{ VARS.CI_REGISTRY_IMAGE }}:prod-${{ github.sha }} registry.digitalocean.com/${{ vars.IMAGE_NAME }}/prod:latest
          docker push registry.digitalocean.com/${{ vars.IMAGE_NAME }}/prod:latest

      - name: Deploy to DigitalOcean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_PROD_APP_ID }}
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
